FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Berg CMS

The Berg CMS uses a simple API allowing consumers to view the stored articles and change them.

## Articles of the Actual Issue [/articles]

### List All Articles [GET]

+ Response 200 (application/json)

        [
            {
                "id": 25,
                "priority": 100,
                "type": "",
                "chapter": "Introduction",
                "title": "Title of the article",
                "header": "Heading part of the article",
                "body": "The main part of the article",
                "footer": "Buttom part of the article",
                "lastchanged": "yyyymmdd-hhmmss;ip:port;user"
            }
        ]


### Get Article [GET /articles/:id]

+ Response 200 (application/json)

        {
            "id": 25,
            "title": "Title of the article",
            "chapter": "Introduction"
        }